# Generated by Django 6.0.6 on 2026-06-08 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("message", models.TextField()),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(2026, 6, 8, 11, 24, 55, 376836)
                    ),
                ),
            ],
        ),
    ]
