# Generated by Django 6.0.6 on 2026-06-08 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
