# Generated by Django 4.1.5 on 2026-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
